return {
    ["errors.not_in_party"] = "Not in party",
    ["errors.only_leader_can_start"] = "Only leader can start matchmaking",
    ["errors.party_empty"] = "Party is empty",
    ["errors.some_members_not_ready"] = "Some party members are not ready",
    ["errors.party_teleport_failed"] = "Party teleport failed",
    ["errors.leave_party_before_solo"] = "Leave the party before starting solo",
    ["errors.teleport_failed"] = "Teleport failed",
}
